package com.epam.esm.dao;

import java.util.List;

/**
 * Interface DAO is designed for basic work with database tables.
 * @param <T> type parameter
 */
public interface DAO<T> {

    /**
     *  Method for getting a list of objects.
     *
     * @return list of objects
     */
    List<T> getAll();

    /**
     * Method for getting an objects by id.
     *
     * @param id  used to find an object
     * @return object
     */
    T getByID(int id);

    /**
     * Method for saving an object.
     *
     * @param t object for saving
     * @return id generated by DB
     */
    long save(T t);

    /**
     * Method for deleting an object.
     *
     * @param id used to delete object
     */
    void delete(int id);
}
